enum EnemyTypes {
	OPEN_OPPONENT_INFO_LISTENER = 'OPEN_OPPONENT_INFO_LISTENER',
	CLOSE_OPPONENT_INFO_LISTENER = 'CLOSE_OPPONENT_INFO_LISTENER',
	GET_OPPONENT_INFO_SUCCESS = 'GET_OPPONENT_INFO_SUCCESS',
	ENEMY_ERROR = 'ENEMY_ERROR',
}

export default EnemyTypes;
