enum UserTypes {
	LOG_IN_START = 'LOG_IN_START',
	LOG_IN_SUCCESS = 'LOG_IN_SUCCESS',
	LOG_OUT_START = 'LOG_OUT_START',
	LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS',
	USER_ERROR = 'USER_ERROR',
}

export default UserTypes;
