enum UserTypes {
	LOG_IN_START = 'LOG_IN_START',
	LOG_IN_SUCCESS = 'LOG_IN_SUCCESS',
	LOG_OUT_START = 'LOG_OUT_START',
	LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS',
	OPEN_CHESS_USER_LISTENER = 'OPEN_CHESS_USER_LISTENER',
	CLOSE_CHESS_USER_LISTENER = 'CLOSE_CHESS_USER_LISTENER',
	FETCH_CHESS_USER_SUCCESS = 'FETCH_CHESS_USER_SUCCESS',
	USER_ERROR = 'USER_ERROR',
}

export default UserTypes;
